spring:
  #Database
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pets
    username: user
    password: 0191

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    open-in-view: false
    generate-ddl: true

# Server configuration
server:
  port: 8080 #set your port